# Generated by Django 2.1.5 on 2019-01-31 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('regno', models.CharField(max_length=10)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_company', models.CharField(choices=[('company', 'Байгууллага'), ('individual', 'Хувь хүн')], max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('regno', models.CharField(max_length=10)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=10)),
                ('engine_number', models.CharField(max_length=30)),
                ('manufacturer', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('variant', models.CharField(max_length=50)),
                ('reg_year', models.DateField()),
                ('mn_reg_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('contract_term', models.CharField(choices=[(12, '12 сараар'), (24, '24 сараар'), (30, '30 сараар'), (36, '36 сараар')], max_length=50)),
                ('plan', models.CharField(choices=[('standard', 'Стандарт'), ('classic', 'Классик'), ('premium', 'Премиум'), ('premium_plus', 'Премиум Плас')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.Insurer', verbose_name='Даатгуулагч')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.Owner', verbose_name='Өмчлөгч')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.Vehicle', verbose_name='Тээврийн хэрэгсэл')),
            ],
        ),
    ]
